DROP TABLE MATCH CASCADE CONSTRAINT;
DROP TABLE SEASON CASCADE CONSTRAINT;
DROP TABLE COACH CASCADE CONSTRAINT;
DROP TABLE CLUB CASCADE CONSTRAINT;
DROP TABLE CATEGORY CASCADE CONSTRAINT;
DROP TABLE TEAM CASCADE CONSTRAINT;
DROP TABLE PLAYER CASCADE CONSTRAINT;
DROP TABLE SECRETARY CASCADE CONSTRAINT;
DROP TABLE TREASURER CASCADE CONSTRAINT;
DROP TABLE VICE_PRESIDENT CASCADE CONSTRAINT;
DROP TABLE PRESIDENT CASCADE CONSTRAINT;
DROP TABLE OFFICE CASCADE CONSTRAINT;
DROP TABLE USERBASKET CASCADE CONSTRAINT;

CREATE TABLE USERBASKET OF T_USER
/
CREATE TABLE OFFICE OF T_OFFICE
/
CREATE TABLE PRESIDENT OF T_PRESIDENT
/
CREATE TABLE VICE_PRESIDENT OF T_VICE_PRESIDENT
/
CREATE TABLE TREASURER OF T_TREASURER
/
CREATE TABLE SECRETARY OF T_SECRETARY
/
CREATE TABLE PLAYER OF T_PLAYER
  NESTED TABLE "TEAM_WITH_PLAYERS" STORE AS "NT_TEAM_WITH_PLAYERS"
/
CREATE TABLE TEAM OF T_TEAM
/
CREATE TABLE CATEGORY OF T_CATEGORY
 NESTED TABLE "LISTTEAM" STORE AS "NT_CATEGORY_TEAM"
/
CREATE TABLE CLUB OF T_CLUB
NESTED TABLE "LISTCATEGORY" STORE AS "NT_CLUB_CATEGORY"
(NESTED TABLE "LISTTEAM" STORE AS "NT_CLUB_TEAM")
/
CREATE TABLE COACH OF "BASKET_USER"."T_COACH"
  NESTED TABLE "TEAM_WITH_COACH" STORE AS "NT_TEAM_WITH_COACH"
/
CREATE TABLE SEASON OF T_SEASON
/
CREATE TABLE MATCH OF T_MATCH
NESTED TABLE DETAILS STORE AS NT_MATCH_DETAILS
/
COMMIT;
