DELETE MATCH;
DELETE SEASON;
DELETE CLUB;
DELETE CATEGORY;
DELETE TEAM;
DELETE PLAYER;
DELETE COACH;
DELETE SECRETARY;
DELETE TREASURER;
DELETE VICE_PRESIDENT;
DELETE PRESIDENT;
DELETE OFFICE;
DELETE USERBASKET;

INSERT INTO USERBASKET VALUES (1,'PHAT','PHAT', 0);
INSERT INTO USERBASKET  VALUES (2,'HOAN','HOAN', 0);

INSERT INTO OFFICE VALUES (
    1,
    SDO_GEOMETRY (
        2001, -- SDO_GTYPE attribute: "2" in 2001 specifies dimensionality is 2.
        8236, -- other fields are set to NULL.
        SDO_POINT_TYPE -- Specifies the coordinates of the point
        (
        106.625061, -- first ordinate, i.e., value in longitude dimension
        10.887254, -- second ordinate, i.e., value in latitude dimension
        NULL -- third ordinate, if any
        ),
        NULL,
        NULL
    ),
    0,
    'OFFICE 1',T_ADDRESS (2,'TAN VIEN','TAN BINH','Ho Chi Minh city'));
INSERT INTO OFFICE VALUES (
    2,
    SDO_GEOMETRY (
        2001, -- SDO_GTYPE attribute: "2" in 2001 specifies dimensionality is 2.
        8236, -- other fields are set to NULL.
        SDO_POINT_TYPE -- Specifies the coordinates of the point
        (
        105.849838, -- first ordinate, i.e., value in longitude dimension
        21.036442, -- second ordinate, i.e., value in latitude dimension
        NULL -- third ordinate, if any
        ),
        NULL,
        NULL
    ),
    0,
    'OFFICE 2',T_ADDRESS (13,'LOT 14 QTSP','12','Ha Noi'));
INSERT INTO OFFICE VALUES (
    3,
    SDO_GEOMETRY (
        2001, -- SDO_GTYPE attribute: "2" in 2001 specifies dimensionality is 2.
        8236, -- other fields are set to NULL.
        SDO_POINT_TYPE -- Specifies the coordinates of the point
        (
       107.045288, -- first ordinate, i.e., value in longitude dimension
       20.985162, -- second ordinate, i.e., value in latitude dimension
        NULL -- third ordinate, if any
        ),
        NULL,
        NULL
    ),
    0,
    'OFFICE 3',T_ADDRESS (93,'CAO THANG','3','Ha Long'));
INSERT INTO OFFICE VALUES (
    4,
    SDO_GEOMETRY (
        2001, -- SDO_GTYPE attribute: "2" in 2001 specifies dimensionality is 2.
        8236, -- other fields are set to NULL.
        SDO_POINT_TYPE -- Specifies the coordinates of the point
        (
       108.456345, -- first ordinate, i.e., value in longitude dimension
       11.956708, -- second ordinate, i.e., value in latitude dimension
        NULL -- third ordinate, if any
        ),
        NULL,
        NULL
    ),
    0,
    'OFFICE 4',T_ADDRESS (1,'LOT 10 QTSP','12','Da Lat'));
INSERT INTO OFFICE VALUES (
    5,
    SDO_GEOMETRY (
        2001, -- SDO_GTYPE attribute: "2" in 2001 specifies dimensionality is 2.
        8236, -- other fields are set to NULL.
        SDO_POINT_TYPE -- Specifies the coordinates of the point
        (
        105.783749, -- first ordinate, i.e., value in longitude dimension
        10.035457, -- second ordinate, i.e., value in latitude dimension
        NULL -- third ordinate, if any
        ),
        NULL,
        NULL
    ),
    0,
    'OFFICE 5',T_ADDRESS (8,'NGUYEN VAN TRANG','1','Can Tho'));

INSERT INTO PRESIDENT VALUES (1,'PRESIDENT 1', 0);
INSERT INTO PRESIDENT VALUES (2,'PRESIDENT 2', 0);
INSERT INTO PRESIDENT VALUES (3,'PRESIDENT 3', 0);
INSERT INTO PRESIDENT VALUES (4,'PRESIDENT 4', 0);
INSERT INTO PRESIDENT VALUES (5,'PRESIDENT 5', 0);

INSERT INTO VICE_PRESIDENT VALUES (1,'VICE_PRESIDENT 1', 0);
INSERT INTO VICE_PRESIDENT VALUES (2,'VICE_PRESIDENT 2', 0);
INSERT INTO VICE_PRESIDENT VALUES (3,'VICE_PRESIDENT 3', 0);
INSERT INTO VICE_PRESIDENT VALUES (4,'VICE_PRESIDENT 4', 0);
INSERT INTO VICE_PRESIDENT VALUES (5,'VICE_PRESIDENT 5', 0);

INSERT INTO TREASURER VALUES (1,'TREASURER 1', 0);
INSERT INTO TREASURER VALUES (2,'TREASURER 2', 0);
INSERT INTO TREASURER VALUES (3,'TREASURER 3', 0);
INSERT INTO TREASURER VALUES (4,'TREASURER 4', 0);
INSERT INTO TREASURER VALUES (5,'TREASURER 5', 0);

INSERT INTO SECRETARY VALUES (1,'SECRETARY 1', 0);
INSERT INTO SECRETARY VALUES (2,'SECRETARY 2', 0);
INSERT INTO SECRETARY VALUES (3,'SECRETARY 3', 0);
INSERT INTO SECRETARY VALUES (4,'SECRETARY 4', 0);
INSERT INTO SECRETARY VALUES (5,'SECRETARY 5', 0);

INSERT INTO TEAM VALUES (1,'TEAM 1', 0);
INSERT INTO TEAM VALUES (2,'TEAM 2', 0);
INSERT INTO TEAM VALUES (3,'TEAM 3', 0);
INSERT INTO TEAM VALUES (4,'TEAM 4', 0);
INSERT INTO TEAM VALUES (5,'TEAM 5', 0);
INSERT INTO TEAM VALUES (6,'TEAM 6', 0);
INSERT INTO TEAM VALUES (7,'TEAM 7', 0);
INSERT INTO TEAM VALUES (8,'TEAM 8', 0);

INSERT INTO PLAYER VALUES 
(
	1,'PLAYER 1', 0, '100001',TO_DATE('18/03/1980','DD/MM/YYYY'),T_ADDRESS ('4','PHAN TON','1','Ho Chi Minh city'),
	T_TEAM_WITH_PLAYER(
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 1),SYSDATE,NULL),
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 2),SYSDATE-300,SYSDATE-200)
	)
);

INSERT INTO PLAYER VALUES 
(
	2,'PLAYER 2', 0, '200001',TO_DATE('18/06/1986','DD/MM/YYYY'),T_ADDRESS ('35','PHAN KE BINH','1','Ha Long'),
	T_TEAM_WITH_PLAYER(
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 1),SYSDATE,NULL),
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 2),SYSDATE-300,SYSDATE-200)
	)
);

INSERT INTO PLAYER VALUES 
(
	3,'PLAYER 3', 0, '300001',TO_DATE('21/05/1978','DD/MM/YYYY'),T_ADDRESS ('27/3A','TRAN NHAN TONG','BA DINH','HA NOI'),
	T_TEAM_WITH_PLAYER(
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 1),SYSDATE,NULL),
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 2),SYSDATE-300,SYSDATE-200)
	)
);

INSERT INTO PLAYER VALUES 
(
	4,'PLAYER 4', 0, '400001',TO_DATE('12/09/1984','DD/MM/YYYY'),T_ADDRESS ('9/4','YET KIEU','HOAN KIEM','Nha Trang'),
	T_TEAM_WITH_PLAYER(
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 1),SYSDATE,NULL),
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 2),SYSDATE-300,SYSDATE-200)
	)
);

INSERT INTO PLAYER VALUES 
(
	5,'PLAYER 5', 0, '500001',TO_DATE('07/05/1981','DD/MM/YYYY'),T_ADDRESS ('18A','LE VAN SY','3','Da Lat'),
	T_TEAM_WITH_PLAYER(
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 3),SYSDATE,NULL),
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 5),SYSDATE-300,SYSDATE-200)
	)
);

INSERT INTO PLAYER VALUES 
(
	6,'PLAYER 6', 0, '600001',TO_DATE('18/03/1982','DD/MM/YYYY'),T_ADDRESS ('4','PHAN TON','1','Can Tho'),
	T_TEAM_WITH_PLAYER(
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 4),SYSDATE,NULL),
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 6),SYSDATE-60,SYSDATE-25)
	)
);

INSERT INTO PLAYER VALUES 
(
	7,'PLAYER 7', 0, '700001',TO_DATE('01/06/1988','DD/MM/YYYY'),T_ADDRESS ('35','PHAN KE BINH','1','Ho Chi Minh city'),
	T_TEAM_WITH_PLAYER(
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 1),SYSDATE,NULL),
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 4),SYSDATE-250,SYSDATE-50)
	)
);

INSERT INTO PLAYER VALUES 
(
	8,'PLAYER 8', 0, '800001',TO_DATE('20/05/1979','DD/MM/YYYY'),T_ADDRESS ('27/3A','TRAN NHAN TONG','BA DINH','Nha Trang'),
	T_TEAM_WITH_PLAYER(
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 5),SYSDATE,NULL),
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 3),SYSDATE-200,SYSDATE-100)
	)
);

INSERT INTO COACH VALUES 
(
	1,'COACH 1', 0,
	T_TEAM_WITH_COACH(
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 1),SYSDATE,NULL),
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 2),SYSDATE-300,SYSDATE-200)
	)
);
INSERT INTO COACH VALUES 
(
	2,'COACH 2', 0,
	T_TEAM_WITH_COACH(
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 3),SYSDATE,NULL),
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 4),SYSDATE-200,SYSDATE-170)
	)
);
INSERT INTO COACH VALUES 
(
	3,'COACH 3', 0,
	T_TEAM_WITH_COACH(
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 5),SYSDATE,NULL),
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 6),SYSDATE-289,SYSDATE-200)
	)
);
INSERT INTO COACH VALUES 
(
	4,'COACH 4', 0,
	T_TEAM_WITH_COACH(
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 7),SYSDATE,NULL),
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 8),SYSDATE-100,SYSDATE-20)
	)
);
INSERT INTO COACH VALUES 
(
	5,'COACH 5', 0,
	T_TEAM_WITH_COACH(
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 3),SYSDATE,NULL),
		T_TEAM_MANY((SELECT REF(T) FROM TEAM T WHERE T.ID = 5),SYSDATE-300,SYSDATE-200)
	)
);

INSERT INTO CATEGORY VALUES (1,'CATEGORY 1',T_TEAMS(), 0);

	INSERT INTO TABLE (SELECT C.LISTTEAM FROM CATEGORY C WHERE C.ID=1)
	SELECT *
	FROM TEAM T
	WHERE T.ID=1;

	INSERT INTO TABLE (SELECT C.LISTTEAM FROM CATEGORY C WHERE C.ID=1)
	SELECT *
	FROM TEAM T
	WHERE T.ID=2;

INSERT INTO CATEGORY VALUES (2,'CATEGORY 2',T_TEAMS(), 0);

	INSERT INTO TABLE (SELECT C.LISTTEAM FROM CATEGORY C WHERE C.ID=2)
	SELECT *
	FROM TEAM T
	WHERE T.ID=3;

	INSERT INTO TABLE (SELECT C.LISTTEAM FROM CATEGORY C WHERE C.ID=2)
	SELECT *
	FROM TEAM T
	WHERE T.ID=4;

INSERT INTO CATEGORY VALUES (3,'CATEGORY 3',T_TEAMS(), 0);

	INSERT INTO TABLE (SELECT C.LISTTEAM FROM CATEGORY C WHERE C.ID=3)
	SELECT *
	FROM TEAM T
	WHERE T.ID=5;

	INSERT INTO TABLE (SELECT C.LISTTEAM FROM CATEGORY C WHERE C.ID=3)
	SELECT *
	FROM TEAM T
	WHERE T.ID=6;

INSERT INTO CATEGORY VALUES (4,'CATEGORY 4',T_TEAMS(), 0);

	INSERT INTO TABLE (SELECT C.LISTTEAM FROM CATEGORY C WHERE C.ID=4)
	SELECT *
	FROM TEAM T
	WHERE T.ID=7;

	INSERT INTO TABLE (SELECT C.LISTTEAM FROM CATEGORY C WHERE C.ID=4)
	SELECT *
	FROM TEAM T
	WHERE T.ID=8;

INSERT INTO CLUB VALUES (1,'CLUB 1', 
	(SELECT REF(O) FROM OFFICE O WHERE O.ID=1),
	(SELECT REF(P) FROM PRESIDENT P WHERE P.ID=1),
	(SELECT REF(V) FROM VICE_PRESIDENT V WHERE V.ID=1),
	(SELECT REF(T) FROM TREASURER T WHERE T.ID=1),
	(SELECT REF(S) FROM SECRETARY S WHERE S.ID=1),
	T_CATEGORIES(), 0);

	INSERT INTO TABLE (SELECT C.LISTCATEGORY FROM CLUB C WHERE C.ID=1)
	SELECT *
	FROM CATEGORY C
	WHERE C.ID=1;

	INSERT INTO TABLE (SELECT C.LISTCATEGORY FROM CLUB C WHERE C.ID=1)
	SELECT *
	FROM CATEGORY C
	WHERE C.ID=2;
	
INSERT INTO CLUB VALUES (2,'CLUB 2',
	(SELECT REF(O) FROM OFFICE O WHERE O.ID=2),
	(SELECT REF(P) FROM PRESIDENT P WHERE P.ID=2),
	(SELECT REF(V) FROM VICE_PRESIDENT V WHERE V.ID=2),
	(SELECT REF(T) FROM TREASURER T WHERE T.ID=2),
	(SELECT REF(S) FROM SECRETARY S WHERE S.ID=2),
	T_CATEGORIES(), 0);

	INSERT INTO TABLE (SELECT C.LISTCATEGORY FROM CLUB C WHERE C.ID=2)
	SELECT *
	FROM CATEGORY C
	WHERE C.ID=3;

	INSERT INTO TABLE (SELECT C.LISTCATEGORY FROM CLUB C WHERE C.ID=2)
	SELECT *
	FROM CATEGORY C
	WHERE C.ID=4;

INSERT INTO SEASON VALUES (1, 'SEASON 1', SYSDATE-550, SYSDATE-450, 0);
INSERT INTO SEASON VALUES (2, 'SEASON 2', SYSDATE-400, SYSDATE-300, 0);
INSERT INTO SEASON VALUES (3, 'SEASON 3', SYSDATE-250, SYSDATE-150, 0);
INSERT INTO SEASON VALUES (4, 'SEASON 4', SYSDATE-100, SYSDATE, 0);

INSERT INTO MATCH VALUES (1, SYSDATE, 
	(SELECT REF(T) FROM TEAM T WHERE ID=1),
	(SELECT REF(T) FROM TEAM T WHERE ID=2),
	(SELECT REF(S) FROM SEASON S WHERE ID=1), T_SCOREDETAILS(), 0);
	
	INSERT INTO TABLE (SELECT M.DETAILS FROM MATCH M WHERE M.ID=1)
		VALUES (1, (SELECT REF(T) FROM TEAM T WHERE T.ID=1), (SELECT REF(P) FROM PLAYER P WHERE P.ID=1), 10);
	INSERT INTO TABLE (SELECT M.DETAILS FROM MATCH M WHERE M.ID=1)
		VALUES (2, (SELECT REF(T) FROM TEAM T WHERE T.ID=1), (SELECT REF(P) FROM PLAYER P WHERE P.ID=2), 20);
	INSERT INTO TABLE (SELECT M.DETAILS FROM MATCH M WHERE M.ID=1)
		VALUES (3, (SELECT REF(T) FROM TEAM T WHERE T.ID=1), (SELECT REF(P) FROM PLAYER P WHERE P.ID=3), 30);

INSERT INTO MATCH VALUES (2, SYSDATE-100,
	(SELECT REF(T) FROM TEAM T WHERE ID=3),
	(SELECT REF(T) FROM TEAM T WHERE ID=4),
	(SELECT REF(S) FROM SEASON S WHERE ID=2), T_SCOREDETAILS(), 0);
	INSERT INTO TABLE (SELECT M.DETAILS FROM MATCH M WHERE M.ID=2)
		VALUES (4, (SELECT REF(T) FROM TEAM T WHERE T.ID=2), (SELECT REF(P) FROM PLAYER P WHERE P.ID=4), 5);
	INSERT INTO TABLE (SELECT M.DETAILS FROM MATCH M WHERE M.ID=2)
		VALUES (5, (SELECT REF(T) FROM TEAM T WHERE T.ID=2), (SELECT REF(P) FROM PLAYER P WHERE P.ID=5), 15);
	INSERT INTO TABLE (SELECT M.DETAILS FROM MATCH M WHERE M.ID=2)
		VALUES (6, (SELECT REF(T) FROM TEAM T WHERE T.ID=2), (SELECT REF(P) FROM PLAYER P WHERE P.ID=6), 25);
    
COMMIT;