	
-- LẤY TOÀN BỘ DỮ LIỆU CỦA BẢNG CON
SELECT N.PERSON_ID
FROM TEAM T,TABLE(T.LISTPLAYER) N
WHERE T.TEAM_ID=1;

SELECT LISTTEAM FROM CATEGORY WHERE LISTTEAM IS A SET AND CATEOGORY_ID=1

-- LẤY GIÁ TRỊ TRONG BẢNG CHA VỚI ĐIỀU KIỆN Ở BẢNG CON
SELECT CATEGORY_ID 
FROM CATEGORY C, TABLE(C.LISTTEAM) LS 
WHERE LS.TEAM_ID=1;

-- DELETE BẢNG CON
DELETE TABLE (SELECT M.DETAILS FROM MATCH M WHERE M.MATCH_ID=1);

-- XÓA BẢNG
DECLARE
V_COUNT NUMBER :=0;
BEGIN
SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME='HELLO';
IF V_COUNT = 1 THEN
	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE HELLO';
	END;
END IF;
END;
/
-- LẤY DỮ LIỆU TỪ BẢNG MANY - MANY
SELECT DEREF(PLAYER).PERSON_ID FROM CLUB_PLAYER CP WHERE CP.ID = 1;
SELECT DEREF(CLUB).CLUB_NAME FROM CLUB_PLAYER CP WHERE CP.ID = 1;

-- GET INFORMATION ABOUT CLUB
SELECT * FROM CLUB;

-- GET INFORMATION ABOUT TEAM
SELECT * FROM TEAM;

-- GET INFORMATION ABOUT PLAYER
SELECT * FROM PLAYER;

-- GET CURRENT CITY OF TEAM
-- Team thuộc Category, Category thuộc club, Club có Address, trong Address có City
SELECT DEREF(CLUB_OFFICE).OFFICE_ADDRESS.ADDRESS_CITY AS CITY_OF_TEAM
FROM CLUB C, TABLE (C.LISTCATEGORY) LS
WHERE LS.CATEGORY_ID = (SELECT CATEGORY_ID 
						FROM CATEGORY C, TABLE(C.LISTTEAM) LS 
						WHERE LS.TEAM_ID=1);

-- THE SCORE MEETINGS PLAYED AT A GIVEN DATE
SELECT M.MATCH_ID, M.MATCH_DATE,TRIM(DEREF(D.TEAM).TEAM_NAME) AS TEAM,DEREF(D.PLAYER).PERSON_NAME AS PLAYER, D.VALUE
FROM MATCH M, TABLE(M.DETAILS) D
WHERE TRUNC(M.MATCH_DATE) = TO_DATE('18-MAR-12');

-- THE LIST OF PLAYER AT A GIVEN DATE
SELECT M.MATCH_ID, M.MATCH_DATE,DEREF(D.PLAYER).PERSON_NAME AS PLAYER
FROM MATCH M, TABLE(M.DETAILS) D
WHERE TRUNC(M.MATCH_DATE) = TO_DATE('18-MAR-12');

-- MEETINGS OF A GIVEN CLUB
SELECT CLUB_ID
FROM CLUB
WHERE CLUB_NAME='CLUB 1'