	
-- LẤY TOÀN BỘ DỮ LIỆU CỦA BẢNG CON
SELECT N.*
FROM TEAM T,TABLE(T.LISTPLAYER) N
WHERE T.TEAM_ID=1;

-- LẤY DỮ LIỆU TỪ BẢNG MANY - MANY
SELECT DEREF(PLAYER).PERSON_ID FROM CLUB_PLAYER CP WHERE CP.ID = 1;
SELECT DEREF(CLUB).CLUB_NAME FROM CLUB_PLAYER CP WHERE CP.ID = 1;