DROP TABLE CLUB_PLAYER CASCADE CONSTRAINT;
DROP TABLE TEAM_COACH CASCADE CONSTRAINT;
DROP TABLE COACH CASCADE CONSTRAINT;
DROP TABLE TEAM CASCADE CONSTRAINT;
DROP TABLE PLAYER CASCADE CONSTRAINT;
DROP TABLE CATEGORY CASCADE CONSTRAINT;
DROP TABLE CLUB CASCADE CONSTRAINT;
DROP TABLE SECRETARY CASCADE CONSTRAINT;
DROP TABLE TREASURER CASCADE CONSTRAINT;
DROP TABLE VICE_PRESIDENT CASCADE CONSTRAINT;
DROP TABLE PRESIDENT CASCADE CONSTRAINT;
DROP TABLE OFFICE CASCADE CONSTRAINT;


CREATE TABLE OFFICE OF T_OFFICE
(
	OFFICE_ID NOT NULL,
	OFFICE_NAME NOT NULL,
	OFFICE_ADDRESS NOT NULL,
	PRIMARY KEY (OFFICE_ID)
)
/
CREATE TABLE PRESIDENT OF T_PRESIDENT
(
	PERSON_ID NOT NULL,
	PERSON_NAME NOT NULL,
	PRIMARY KEY (PERSON_ID)
)
/
CREATE TABLE VICE_PRESIDENT OF T_VICE_PRESIDENT
(
	PERSON_ID NOT NULL,
	PERSON_NAME NOT NULL,
	PRIMARY KEY (PERSON_ID)
)
/
CREATE TABLE TREASURER OF T_TREASURER
(
	PERSON_ID NOT NULL,
	PERSON_NAME NOT NULL,
	PRIMARY KEY (PERSON_ID)
)
/
CREATE TABLE SECRETARY OF T_SECRETARY
(
	PERSON_ID NOT NULL,
	PERSON_NAME NOT NULL,
	PRIMARY KEY (PERSON_ID)
)
/
CREATE TABLE PLAYER OF T_PLAYER
(
	PERSON_ID NOT NULL,
	PERSON_NAME NOT NULL,
	PLAYER_LICENCE_NUMBER NOT NULL,
	PLAYER_BIRTHDAY NOT NULL,
	PLAYER_ADDRESS NOT NULL,
	PRIMARY KEY (PERSON_ID)
)
/

CREATE TABLE TEAM OF T_TEAM
(
	TEAM_ID NOT NULL,
	TEAM_NAME NOT NULL,
	LISTPLAYER NULL,
	PRIMARY KEY (TEAM_ID)
)
NESTED TABLE LISTPLAYER STORE AS NT_TEAM_PLAYER
/

CREATE TABLE CATEGORY OF T_CATEGORY
(
	CATEGORY_ID NOT NULL,
	CATEGORY_NAME NOT NULL,
	LISTTEAM NULL,
	PRIMARY KEY (CATEGORY_ID)
)
NESTED TABLE LISTTEAM STORE AS NT_CATEGORY_TEAM
(NESTED TABLE LISTPLAYER STORE AS NT_CATEGORY_PLAYERS)
/

CREATE TABLE CLUB OF T_CLUB
(
	CLUB_ID NOT NULL,
	CLUB_NAME NOT NULL,
	CLUB_OFFICE NOT NULL,
	CLUB_PRESIDENT NOT NULL,
	CLUB_VICE_PRESIDENT NOT NULL,
	CLUB_TREASURER NOT NULL,
	CLUB_SECRETARY NOT NULL,
	LISTCATEGORY NULL,
	PRIMARY KEY (CLUB_ID)
)
NESTED TABLE LISTCATEGORY STORE AS NT_CLUB_CATEGORY
	(NESTED TABLE LISTTEAM STORE as NT_CLUB_TEAM
		(NESTED TABLE LISTPLAYER STORE AS NT_CLUB_PLAYER))
/

CREATE TABLE COACH OF T_COACH
(
	PERSON_ID NOT NULL,
	PERSON_NAME NOT NULL,
	PRIMARY KEY (PERSON_ID)
)
/
CREATE TABLE TEAM_COACH OF T_TEAM_COACH
(
	ID NOT NULL,
	TEAM NOT NULL,
	COACH NOT NULL,
	STARTDATE DEFAULT SYSDATE,
	ENDDATE DEFAULT SYSDATE + 365,
	PRIMARY KEY (ID)
)
/
CREATE TABLE CLUB_PLAYER OF T_CLUB_PLAYER
(
	ID NOT NULL,
	CLUB NOT NULL,
	PLAYER NOT NULL,
	JOINED_DATE DEFAULT SYSDATE,
	PRIMARY KEY (ID)
)
/

CREATE TABLE MATCH OF T_MATCH
(
	MATCH_ID NOT NULL,
	MATCH_DATE DEFAULT SYSDATE,
	DETAILS NULL,
	PRIMARY KEY (MATCH_ID)
)
NESTED TABLE DETAILS STORE AS NT_MATCH_DETAILS
/
