CREATE PROCEDURE SP_SAVE_OFFICE
(ID INT, OFFICE_NAME VARCHAR, 
ADDRESS_NUMBER VARCHAR,	ADDRESS_STREET VARCHAR, ADDRESS_DISTRICT VARCHAR,ADDRESS_CITY VARCHAR)
(
INSERT INTO OFFICE VALUES (1,'OFFICE 1',T_ADDRESS (2,'TAN VIEN','TAN BINH','HCMC'));

)